name = "E. Coli"
author = "AmeMeida"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1aed5d01b6ab7a170ee6615eade2fdab082af04cb8a35128afdc75a8dde3a96"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
