name = "E. Coli"
author = "AmeMeida"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e804a1de3e2ce8026b0031e2eb0c0aa5b7eb2097637df040acd7cc210f80ca"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
