name = "E. Coli"
author = "AmeMeida"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d31e4da03ff80ad633c220309ee615cdeed9e77068e874fa78f7d7c80bd6dd0f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
